"""Synchronous Protocol contracts for Implementation Ledger repositories.

The future PostgreSQL adapter may be asynchronous at its application boundary.
These contracts deliberately describe persistence-independent behavior and do
not own commit, rollback, Session, or Unit of Work concerns.
"""

from __future__ import annotations

from typing import Protocol, Sequence

from .enums import CanonicalStatus, ConsistencyStatus, ImplementationTaskStatus, RunRelationshipType
from .models import (
    ArchitectureDecisionReference,
    ChangedFile,
    ChangedSymbol,
    ComponentReference,
    ImplementationArtifact,
    ImplementationRun,
    ImplementationTask,
    Limitation,
    RecommendedTask,
    RunRelationship,
    TestExecution,
)
from .repository_queries import HistoryQuery, Page, RunQuery, TaskQuery


class ImplementationTaskRepository(Protocol):
    def create_task(self, task: ImplementationTask) -> ImplementationTask: ...
    def get_task(self, task_id: str) -> ImplementationTask | None: ...
    def require_task(self, task_id: str) -> ImplementationTask: ...
    def get_task_version(self, task_id: str) -> int: ...
    def list_tasks(self, query: TaskQuery) -> Page[ImplementationTask]: ...
    def update_task_status(
        self,
        task_id: str,
        new_status: ImplementationTaskStatus,
        expected_version: int,
    ) -> ImplementationTask: ...


class ImplementationRunRepository(Protocol):
    def create_run(self, run: ImplementationRun) -> ImplementationRun: ...
    def get_run(self, run_id: str) -> ImplementationRun | None: ...
    def require_run(self, run_id: str) -> ImplementationRun: ...
    def get_run_version(self, run_id: str) -> int: ...
    def list_runs(self, query: RunQuery) -> Page[ImplementationRun]: ...
    def finalize_run(
        self,
        run_id: str,
        terminal_run: ImplementationRun,
        expected_version: int,
    ) -> ImplementationRun: ...
    def set_consistency_status(
        self,
        run_id: str,
        status: ConsistencyStatus,
        expected_version: int,
    ) -> ImplementationRun: ...
    def set_canonical_status(
        self,
        run_id: str,
        status: CanonicalStatus,
        expected_version: int,
    ) -> ImplementationRun: ...


class RunRelationshipRepository(Protocol):
    def add_relationship(self, relationship: RunRelationship) -> RunRelationship: ...
    def get_relationship(self, relationship_id: str) -> RunRelationship | None: ...
    def require_relationship(self, relationship_id: str) -> RunRelationship: ...
    def list_outgoing_relationships(self, run_id: str) -> tuple[RunRelationship, ...]: ...
    def list_incoming_relationships(self, run_id: str) -> tuple[RunRelationship, ...]: ...
    def relationship_exists(
        self,
        source_run_id: str,
        target_run_id: str,
        relationship_type: RunRelationshipType,
    ) -> bool: ...
    def would_create_cycle(self, source_run_id: str, target_run_id: str) -> bool: ...


class RunDetailRepository(Protocol):
    def append_changed_file(self, item: ChangedFile) -> ChangedFile: ...
    def append_changed_symbol(self, item: ChangedSymbol) -> ChangedSymbol: ...
    def append_test_execution(self, item: TestExecution) -> TestExecution: ...
    def append_artifact(self, item: ImplementationArtifact) -> ImplementationArtifact: ...
    def append_component_reference(self, item: ComponentReference) -> ComponentReference: ...
    def append_adr_reference(
        self, item: ArchitectureDecisionReference
    ) -> ArchitectureDecisionReference: ...
    def append_limitation(self, item: Limitation) -> Limitation: ...
    def append_recommended_task(self, item: RecommendedTask) -> RecommendedTask: ...
    def list_changed_files(self, run_id: str) -> tuple[ChangedFile, ...]: ...
    def list_changed_symbols(self, run_id: str) -> tuple[ChangedSymbol, ...]: ...
    def list_test_executions(self, run_id: str) -> tuple[TestExecution, ...]: ...
    def list_artifacts(self, run_id: str) -> tuple[ImplementationArtifact, ...]: ...
    def list_component_references(self, run_id: str) -> tuple[ComponentReference, ...]: ...
    def list_adr_references(
        self, run_id: str
    ) -> tuple[ArchitectureDecisionReference, ...]: ...
    def list_limitations(self, run_id: str) -> tuple[Limitation, ...]: ...
    def list_recommended_tasks(self, run_id: str) -> tuple[RecommendedTask, ...]: ...
    def list_run_history(self, query: HistoryQuery) -> Page[ImplementationRun]: ...
    def record_run_details_atomic(
        self,
        run: ImplementationRun,
        *,
        changed_files: Sequence[ChangedFile] = (),
        changed_symbols: Sequence[ChangedSymbol] = (),
        tests: Sequence[TestExecution] = (),
        artifacts: Sequence[ImplementationArtifact] = (),
        component_refs: Sequence[ComponentReference] = (),
        adr_refs: Sequence[ArchitectureDecisionReference] = (),
        limitations: Sequence[Limitation] = (),
        recommended_tasks: Sequence[RecommendedTask] = (),
    ) -> ImplementationRun: ...


class LedgerRepository(Protocol):
    @property
    def task_repository(self) -> ImplementationTaskRepository: ...

    @property
    def run_repository(self) -> ImplementationRunRepository: ...

    @property
    def relationship_repository(self) -> RunRelationshipRepository: ...

    @property
    def detail_repository(self) -> RunDetailRepository: ...
