from enum import Enum


class ArtifactKind(str, Enum):
    DATASET_SNAPSHOT = "dataset_snapshot"
    FACTOR_VALUES = "factor_values"
    FACTOR_OPTIMIZATION = "factor_optimization"
    VALIDATION_DATASET = "validation_dataset"
    FACTOR_VALIDATION_RESULT = "factor_validation_result"
    FROZEN_TEST_RESULT = "frozen_test_result"
    FACTOR_REGISTRY = "factor_registry"
    REGISTRY_RECONCILIATION = "registry_reconciliation"
    FRESH_VALIDATION_ADMISSION = "fresh_validation_admission"
    RESEARCH_CAMPAIGN = "research_campaign"
    FRESH_VALIDATION_ACCRUAL = "fresh_validation_accrual"
    FRESH_VALIDATION_RESULT = "fresh_validation_result"
    IMPLEMENTATION_EVIDENCE = "implementation_evidence"
    GENERIC_RESEARCH_BUNDLE = "generic_research_bundle"
    FIXED_UNIVERSE_LOCK = "fixed_universe_lock"
    FIXED_UNIVERSE_HISTORICAL_DATASET = "fixed_universe_historical_dataset"
    HISTORICAL_AGENT_EXPERIMENT = "historical_agent_experiment"
    HISTORICAL_ROUND_LOCK = "historical_round_lock"
    HISTORICAL_ROUND_EVALUATION = "historical_round_evaluation"
    QLIB_BACKTEST_RESULT = "qlib_backtest_result"
    HISTORICAL_HOLDOUT_RESULT = "historical_holdout_result"
    AGENT_ITERATION_ASSESSMENT = "agent_iteration_assessment"
    SIGNAL_MISSINGNESS_AUDIT = "signal_missingness_audit"
    HISTORICAL_BACKTEST_FOLLOWUP = "historical_backtest_followup"
    TUSHARE_500_UNIVERSE_LOCK = "tushare_500_universe_lock"
    TUSHARE_100_EXPERIMENT_UNIVERSE_LOCK = "tushare_100_experiment_universe_lock"
    TUSHARE_RAW_DAILY = "tushare_raw_daily"
    TUSHARE_RAW_ADJ_FACTOR = "tushare_raw_adj_factor"
    TUSHARE_RAW_DAILY_BASIC = "tushare_raw_daily_basic"
    TUSHARE_TRADE_CALENDAR = "tushare_trade_calendar"
    TUSHARE_MARKET_BENCHMARK = "tushare_market_benchmark"
    TUSHARE_NORMALIZED_BARS = "tushare_normalized_bars"
    TUSHARE_FEATURE_DATASET = "tushare_feature_dataset"
    TUSHARE_LABEL_DATASET = "tushare_label_dataset"
    TUSHARE_100_QLIB_VIEW = "tushare_100_qlib_view"
    TUSHARE_RESEARCH_REGISTRY_GENESIS = "tushare_research_registry_genesis"
    SANITIZED_RESEARCH_MEMORY = "sanitized_research_memory"
    DATA_AUTHORITY_RECORD = "data_authority_record"
    LEGACY_DATA_PURGE_PLAN = "legacy_data_purge_plan"
    LEGACY_DATA_PURGE_RESULT = "legacy_data_purge_result"
    TUSHARE_HISTORICAL_AGENT_EXPERIMENT = "tushare_historical_agent_experiment"
    TUSHARE_HISTORICAL_ROUND_LOCK = "tushare_historical_round_lock"
    TUSHARE_HISTORICAL_ROUND_EVALUATION = "tushare_historical_round_evaluation"
    TUSHARE_QLIB_BACKTEST_RESULT = "tushare_qlib_backtest_result"
    TUSHARE_HISTORICAL_HOLDOUT_RESULT = "tushare_historical_holdout_result"
    TUSHARE_AGENT_ITERATION_ASSESSMENT = "tushare_agent_iteration_assessment"
    TUSHARE_HISTORICAL_EXPERIMENT_REGISTRY = "tushare_historical_experiment_registry"


class IntegrityStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    CORRUPT = "corrupt"
