"""Async application-facing mirror of the frozen synchronous Ledger contract."""

from __future__ import annotations

from typing import Protocol, Sequence

from backend.services.engine.project_knowledge.domain.enums import (
    CanonicalStatus,
    ConsistencyStatus,
    ImplementationTaskStatus,
    RunRelationshipType,
)
from backend.services.engine.project_knowledge.domain.models import (
    ArchitectureDecisionReference,
    ChangedFile,
    ChangedSymbol,
    ComponentReference,
    ImplementationArtifact,
    ImplementationRun,
    ImplementationTask,
    Limitation,
    RecommendedTask,
    RunRelationship,
    TestExecution,
)
from backend.services.engine.project_knowledge.domain.repository_queries import (
    HistoryQuery,
    Page,
    RunQuery,
    TaskQuery,
)


class AsyncLedgerRepository(Protocol):
    async def create_task(self, task: ImplementationTask) -> ImplementationTask: ...
    async def get_task(self, task_id: str) -> ImplementationTask | None: ...
    async def require_task(self, task_id: str) -> ImplementationTask: ...
    async def get_task_version(self, task_id: str) -> int: ...
    async def list_tasks(self, query: TaskQuery) -> Page[ImplementationTask]: ...
    async def update_task_status(self, task_id: str, new_status: ImplementationTaskStatus, expected_version: int) -> ImplementationTask: ...

    async def create_run(self, run: ImplementationRun) -> ImplementationRun: ...
    async def get_run(self, run_id: str) -> ImplementationRun | None: ...
    async def require_run(self, run_id: str) -> ImplementationRun: ...
    async def get_run_version(self, run_id: str) -> int: ...
    async def list_runs(self, query: RunQuery) -> Page[ImplementationRun]: ...
    async def finalize_run(self, run_id: str, terminal_run: ImplementationRun, expected_version: int) -> ImplementationRun: ...
    async def set_consistency_status(self, run_id: str, status: ConsistencyStatus, expected_version: int) -> ImplementationRun: ...
    async def set_canonical_status(self, run_id: str, status: CanonicalStatus, expected_version: int) -> ImplementationRun: ...

    async def add_relationship(self, relationship: RunRelationship) -> RunRelationship: ...
    async def get_relationship(self, relationship_id: str) -> RunRelationship | None: ...
    async def require_relationship(self, relationship_id: str) -> RunRelationship: ...
    async def list_outgoing_relationships(self, run_id: str) -> tuple[RunRelationship, ...]: ...
    async def list_incoming_relationships(self, run_id: str) -> tuple[RunRelationship, ...]: ...
    async def relationship_exists(self, source_run_id: str, target_run_id: str, relationship_type: RunRelationshipType) -> bool: ...
    async def would_create_cycle(self, source_run_id: str, target_run_id: str) -> bool: ...

    async def append_changed_file(self, item: ChangedFile) -> ChangedFile: ...
    async def append_changed_symbol(self, item: ChangedSymbol) -> ChangedSymbol: ...
    async def append_test_execution(self, item: TestExecution) -> TestExecution: ...
    async def append_artifact(self, item: ImplementationArtifact) -> ImplementationArtifact: ...
    async def append_component_reference(self, item: ComponentReference) -> ComponentReference: ...
    async def append_adr_reference(self, item: ArchitectureDecisionReference) -> ArchitectureDecisionReference: ...
    async def append_limitation(self, item: Limitation) -> Limitation: ...
    async def append_recommended_task(self, item: RecommendedTask) -> RecommendedTask: ...
    async def list_changed_files(self, run_id: str) -> tuple[ChangedFile, ...]: ...
    async def list_changed_symbols(self, run_id: str) -> tuple[ChangedSymbol, ...]: ...
    async def list_test_executions(self, run_id: str) -> tuple[TestExecution, ...]: ...
    async def list_artifacts(self, run_id: str) -> tuple[ImplementationArtifact, ...]: ...
    async def list_component_references(self, run_id: str) -> tuple[ComponentReference, ...]: ...
    async def list_adr_references(self, run_id: str) -> tuple[ArchitectureDecisionReference, ...]: ...
    async def list_limitations(self, run_id: str) -> tuple[Limitation, ...]: ...
    async def list_recommended_tasks(self, run_id: str) -> tuple[RecommendedTask, ...]: ...
    async def list_run_history(self, query: HistoryQuery) -> Page[ImplementationRun]: ...
    async def record_run_details_atomic(
        self,
        run: ImplementationRun,
        *,
        changed_files: Sequence[ChangedFile] = (),
        changed_symbols: Sequence[ChangedSymbol] = (),
        tests: Sequence[TestExecution] = (),
        artifacts: Sequence[ImplementationArtifact] = (),
        component_refs: Sequence[ComponentReference] = (),
        adr_refs: Sequence[ArchitectureDecisionReference] = (),
        limitations: Sequence[Limitation] = (),
        recommended_tasks: Sequence[RecommendedTask] = (),
    ) -> ImplementationRun: ...
